---
name: Modules.Tizen.Apps.Application
summary: |
    This interface defines the current application's information and the basic operations (such as 
    exit or hide) for the current application.
extends: Titanium.Proxy
createable: false
methods:
  - name: exit
    summary: Exits the current application.
  - name: hide
    summary: Hides the current application. 
  - name: getRequestedAppControl
    summary: Gets the requested application control passed to the current application. 
    description: |
        Gets the requested application control that contains the application control passed by the 
        [launchAppControl](Modules.Tizen.Apps.launchAppControl) method from the calling application. 
        The requested application control 
        contains the reason the application was launched and what it has to perform. For example, an 
        application might be launched to display an image on a page by other application's request. 
        In all of these cases, the application is responsible for checking the contents of the 
        application control and responding appropriately when it is launched.
    returns: 
      - type: Modules.Tizen.Apps.RequestedApplicationControl
        summary: The details of an requested application control

properties:
  - name: appInfo
    summary: An attribute to store the application information for the current application. 
    type: Modules.Tizen.Apps.ApplicationInformation
    permission: read-only

  - name: contextId
    summary: An attribute to store the ID of a running application. 
    type: String
    permission: read-only
